name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Tạo thư mục docs nếu không có
          mkdir -p docs
          
          # Sao chép file build vào docs/
          cp -r out/* docs/
          
          cd docs
          git add -A
          
          # Kiểm tra sự thay đổi và commit
          git diff --quiet || git commit -m "Deploy to GitHub Pages"
          
          # Push lên GitHub Pages
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/nthanhdo/review.git
          git push origin master
          echo ${{ secrets.GH_TOKEN }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
